### ISSUE TITLE
Feature - add host to custom groups from path tree

### ISSUE THREAD

**Issue by eusebium** [Manuelraa/yaml_folder_inventory#57]
Hi, it is possible to add host to custom groups from entire path?

Example:
From hosts in file:
./inventory/service/type/environment/main.yml
to:
* hosts in groups:
- service
- service_type
- service_type_environment
- environment  (this is already implemented)

**Comment by Manuelraa** [comment]
Thank you for the request!

Currently there is no good way to achieve this.
There is a special variable `groups` which can be set to override groups a host belongs to.
Which is not what you look for. As you would need some way to add additional groups.

I can see the value in a optional "level groups" feature which would automatically generate groups for each level (`service`, `service_type`, ...)
I should find time today for the implementation.

Also a special variable for adding additional groups would be useful

**Comment by Manuelraa** [comment]
I will release version `1.5.0` once #59 is merged. It then will have a new config option `enable_level_groups` which will add this feature.
